### ISSUE TITLE
scss-lint - DuplicateProperty conflict

### ISSUE THREAD

**Issue by paulrrdiaz** [ableco/ablecop#22]
I'm working on F- right now, I'm using a mixin that return the font-size on rem and px to cover browser without rem support

```
@mixin font-size($font-value : map-get($font-styles, base-font-size), $base-font-value : map-get($font-styles, base-font-size), $base-line-value : map-get($font-styles, base-line-height)) {
  font-size: #{$font-value}px;
  font-size: #{($font-value / $base-font-value)}rem;
  line-height: #{($font-value / $base-font-value) * $base-line-value}px;
  line-height: #{($base-line-value / $base-font-value) * ($font-value / $base-font-value)}rem;
}
```

So, I think we could set false DuplicateProperty or do something like:

```
DuplicateProperty:
    enabled: true
    ignore_consecutive:
      - background
      - font-size
      - line-height
```

I'm using these 3 properties in mixins for now.
